fix power-menu first attempt

diff --git a/bin/power-menu b/bin/power-menu
--- a/bin/power-menu
+++ b/bin/power-menu
@@ -1,24 +1,76 @@
 #!/bin/bash
 
-# Original reference https://github.com/basecamp/omarchy/blob/dev/bin/omarchy-menu-power
-# ======================================================================================
-# Based on Omarchy script: omarchy-menu-power
-# ======================================================================================
+# All supported choices
+all=(shutdown reboot suspend hibernate logout lockscreen)
 
-# First, check if Rofi is running. If it is, kill it and exit.
-if pgrep -x rofi >/dev/null; then
-    pkill -x rofi
-    exit 0
+# By default, show all (i.e., just copy the array)
+show=("${all[@]}")
+
+declare -A texts
+texts[lockscreen]="Lock Screen"
+texts[logout]="Log Out"
+texts[suspend]="Suspend"
+texts[hibernate]="Hibernate"
+texts[reboot]="Reboot"
+texts[shutdown]="Shut Down"
+
+declare -A icons
+icons[lockscreen]=""
+icons[logout]="󰍃"
+icons[suspend]="󰤄"
+icons[hibernate]=""
+icons[reboot]="󰜉"
+icons[shutdown]="󰐥"
+
+declare -A actions
+actions[lockscreen]="hyprlock"
+actions[logout]="loginctl terminate-session ${XDG_SESSION_ID-}"
+actions[suspend]="systemctl suspend-then-hibernate &>/dev/null || hyprlock && systemctl suspend"
+actions[hibernate]="systemctl hibernate &>/dev/null || hyprlock && systemctl suspend"
+actions[reboot]="systemctl reboot"
+actions[shutdown]="systemctl poweroff"
+
+function write_message {
+  local icon="<span font_size=\"medium\">$1</span>"
+  local text="<span font_size=\"medium\">$2</span>"
+  echo -n "\u200e$icon \u2068$text\u2069"
+}
+
+function print_selection {
+  echo -e "$1" | $(read -r -d '' entry; echo "echo $entry")
+}
+
+declare -A messages
+
+for entry in "${all[@]}"; do
+  messages[$entry]=$(write_message "${icons[$entry]}" "${texts[$entry]^}")
+done
+
+if [ $# -gt 0 ]; then
+  # If arguments given, use those as the selection
+  selection="${@}"
+else
+  exit 0
 fi
 
-selection=$(uwsm app -- rofi -show power-menu -modi "power-menu:${HOME}/.local/share/anarchy/default/scripts/power-menu-options" \
-             -theme-str 'element { children: [element-text]; } inputbar {  enabled: false; } window { width: 250; }')
+# Don't allow custom entries
+echo -e "\0no-custom\x1ftrue"
+# Use markup
+echo -e "\0markup-rows\x1ftrue"
 
-case "$selection" in
-*Logout*) uwsm stop ;;
-*Lock*) hyprlock ;;
-*Suspend*) systemctl suspend-then-hibernate &>/dev/null || systemctl suspend ;;
-*Hibernate*) systemctl hibernate &>/dev/null || systemctl suspend ;;
-*Restart*) systemctl reboot ;;
-*Shutdown*) systemctl poweroff ;;
-esac
+if [ -z "${selection+x}" ]; then
+  for entry in "${show[@]}"; do
+    echo -e "${messages[$entry]}\0icon\x1f${icons[$entry]}"
+  done
+else
+  for entry in "${show[@]}"; do
+    if [ "$selection" = "$(print_selection "${messages[$entry]}")" ]; then
+      # Perform the action
+      ${actions[$entry]}
+      exit 0
+    fi
+  done
+  # The selection didn't match anything, so raise an error
+  echo "Invalid selection: $selection" >&2
+  exit 1
+fi
